### ISSUE TITLE
Attempt to simplify installation

### ISSUE THREAD

**Issue by Smith0r** [Smith0r/bulletin#63]
Attempt to automatically acquire site protocol, url, and subfolder (if applicable).
Also, add a new field for Site Name.

**Comment by rbertram90** [comment]
Hi, was just trying out your project, had a couple of install issues - the installer.lock file is included in the repo so on a fresh install you don't get redirected to the install page (just get 404).

You've mentioned about automatic detection of url and protocol above, if you exclude .htaccess from the repo (as this has hardcoded values) and have both domain + protocol fields in the install form - defaulted using $_SERVER variables - should be an easy win in that gives user best of both worlds?

Really intrigued to see the rest of the app, just haven't managed login without errors yet 🤓

**Comment by Smith0r** [comment]
@rbertram90 Ah yeah, the installer.lock is included in the repo because I'm developing directly into the folder synchronized to GitHub, I suppose it would make sense to remove everything related to locking the installer, configuration etc, in case someone clones the repo!

Using the $_SERVER variables was the plan as it's definitely way too complicated for newcomers (I even got it wrong trying to install my own application fresh, so there's a big red flag!), i'll make that change ASAP!

Thanks for taking the time to try it and comment, really helps move everything along! 😄
