### ISSUE TITLE
Routing issues

### ISSUE THREAD

**Issue by rbertram90** [Smith0r/bulletin#81]
Have now got the app fully functioning - had a problem where it was not routing correctly so could not access anything but the homepage. I'd set up a virtual host (bulletin.localhost), installed the app, but when clicking login it was trying to use the category controller to run login.

Found the issue was /core/classes/core.php line 325 _(comment says it all!)_:
`$string = str_replace(SUBFOLDER, "", $string); // Remove after putting live`

And then line 352 `$parts = explode("/", $task_split["0"]);` where $parts[0] was being set to an empty string

So adding: `if (strlen($parts[0]) == 0) array_shift($parts);` on line 353 fixed my issues and everything magically started working 😃 

P.S. Thanks for the install changes - worked a charm.

**Comment by Smith0r** [comment]
Gah! Routing is the thing that's caused me the most trouble, it's a pain in the neck but it makes such nice URLs...

I've implemented your fix, it works for me and I assume it's working for you now so i'll close this off.

Thanks again for testing and again contributing to the project! 😄
